version: '3'
services:
  albpz_server:
    build:
      context: '.'
      dockerfile: 'Dockerfile-server'
    container_name: 'albpz_server'
    depends_on:
      - 'albpz_db'
    networks:
      - 'backend'
    ports: 
      - '80:80'
    volumes:
      - './public:/var/www/Albertos_Pizza/public/'
      - './src:/var/www/Albertos_Pizza/src/'
      - './vendor:/var/www/Albertos_Pizza/vendor/'
  albpz_db:
    build:
      context: '.'
      dockerfile: 'Dockerfile-db'
    container_name: 'albpz_db'
    networks:
      - 'backend'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
networks:
  backend:
volumes:
  mysql: